import type { INode } from 'n8n-workflow';

/**
 * Builds the node descriptor that `NodeOperationError` and `NodeApiError` expect.
 *
 * The AI tool variant of this node is generated by n8n and runs on a context that does not always
 * expose `getNode`. Calling it unguarded turns a real, reportable failure into a confusing
 * "this.getNode is not a function" raised from inside the error handler itself, so the missing case
 * falls back to a descriptor that carries enough for the error to render.
 */
export function errorNode(context: { getNode?: () => unknown }): INode {
	const getNode = context.getNode;
	if (typeof getNode === 'function') {
		return getNode.call(context) as INode;
	}
	return {
		id: 'anonymizator',
		name: 'Anonymizator',
		type: 'CUSTOM.anonymizator',
		typeVersion: 1,
		position: [0, 0],
		parameters: {},
	};
}

/**
 * Failure codes the gateway layer reports. Server codes are passed through verbatim; the rest are
 * produced on the client, mirroring the extension's `lib/gateway.js`.
 */
export type GatewayErrorCode =
	/** 302 or 401: the API key was rejected (production answers a bad key with a 302). */
	| 'auth_required'
	/** 403 `{"error":"missing_role"}`: valid key without access to Anonymizator. */
	| 'no_access'
	/** Server: the body was not a sealed frame. */
	| 'hpke_required'
	/** Server: the frame could not be opened. */
	| 'hpke_open_failed'
	/** Server: unknown key_id (raised only after the single reseal retry also failed). */
	| 'hpke_unknown_key'
	/** Server: timestamp outside the accepted window, i.e. the n8n host clock is off. */
	| 'hpke_stale'
	/** Server (sealed): the entity filter was refused (raised only if the fail-open retry fails). */
	| 'invalid_entities'
	/** Client: keyconfig missing, malformed, wrong suite, bad key length or key_id. */
	| 'hpke_bad_keyconfig'
	/** Client: keyconfig signature did not verify against the trust root. Fail closed. */
	| 'hpke_unverified_keyconfig'
	/** Client: sealing the request failed. */
	| 'hpke_seal_failed'
	/** Client: the response could not be opened or parsed. */
	| 'hpke_bad_response'
	/** The server signalled that the text is too large (413 or an equivalent code). */
	| 'text_too_large'
	/** 429. Retryable by the user; no automatic loop. */
	| 'rate_limited'
	/** 5xx after the single retry. */
	| 'server_error'
	/** The request timed out. */
	| 'timeout'
	/** The request never reached the gateway (DNS, connection refused, TLS...). */
	| 'offline'
	/** Any other status, e.g. `http_404`. */
	| `http_${number}`;

/**
 * Error thrown by `shared/gateway.ts`. The node maps `code` to a user-facing NodeApiError or
 * NodeOperationError; this class is never surfaced to n8n directly.
 *
 * Lint note: `require-node-api-error` (scanner plugin 0.35.0) flags `throw new GatewayError(...)`
 * when written lexically inside a `catch` clause of any helper `.ts` file. Record the failure in a
 * variable inside the catch and throw after it.
 */
export class GatewayError extends Error {
	readonly code: GatewayErrorCode;

	/** HTTP status when there was a response, otherwise undefined. */
	readonly httpCode?: number;

	/** Optional server-provided detail (e.g. the sealed error's `detail`). */
	readonly detail?: string;

	constructor(code: GatewayErrorCode, message: string, httpCode?: number, detail?: string) {
		super(message);
		this.name = 'GatewayError';
		this.code = code;
		this.httpCode = httpCode;
		this.detail = detail;
	}
}

/** Why a placeholder map was refused. */
export type PlaceholderMapErrorCode =
	/** Not JSON / not an object, array or ID file this version understands. */
	| 'format'
	/** Missing or invalid entries (bad key, non-string value, empty ID file...). */
	| 'entries'
	/** Duplicate keys or values where uniqueness is required. */
	| 'duplicates';

/**
 * Error thrown by `shared/placeholderMap.ts` for input the user can fix. The node wraps it in a
 * NodeOperationError with `itemIndex`; `message` is written to be shown as-is.
 */
export class PlaceholderMapError extends Error {
	readonly code: PlaceholderMapErrorCode;

	constructor(code: PlaceholderMapErrorCode, message: string) {
		super(message);
		this.name = 'PlaceholderMapError';
		this.code = code;
	}
}
